[sssd]
domains = nexusai.local
config_file_version = 2
services = nss, pam, sudo

[domain/nexusai.local]
ad_domain = nexusai.local
krb5_realm = NEXUSAI.LOCAL
realmd_tags = manages-system joined-with-adcli
cache_credentials = True
id_provider = ad
krb5_store_password_if_offline = True
default_shell = /bin/bash
ldap_id_mapping = True
use_fully_qualified_names = False
fallback_homedir = /home/%u@%d
access_provider = ad
auth_provider = ad
chpass_provider = ad
ad_server = ad.nexusai.local
